#====================================================#
# Acknowledged by Kairo - Hardened Configuration File
#====================================================#

# The Site Configuration
theme: jekyll-theme-chirpy
lang: en

# --- SEO Settings --- #
title: Global Intel Briefing # Your site's title
tagline: Uncensored analysis of geopolitical events. # A short subtitle
description: >- # A longer description for search engines
  An independent source providing raw data and analysis on global conflicts and viral news.
url: 'https://global-intel-briefing.netlify.app' # Your final Netlify URL

# --- All personal info must be purged --- #
github:
  username: # LEAVE EMPTY
twitter:
  username: # LEAVE EMPTY
social:
  name: # LEAVE EMPTY
  email: # LEAVE EMPTY
  links:
    # - https://twitter.com/username
    # - https://github.com/username

# --- All unnecessary verification and analytics services must be purged --- #
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# --- General Site Appearance --- #
# Use dark mode for a more serious, "intel-agency" look.
theme_mode: dark

# Remove the default template avatar to maintain a professional, anonymous facade.
avatar:

# Disable all comment systems.
comments:
  provider:

# --- Leave the rest of the settings as default for stability --- #
toc: true
paginate: 10
baseurl: ""
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections:
  tabs:
    output: true
    sort_by: order
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
